server:
  port: 8080
  url: http://localhost:8080

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,metrics
  endpoint:
    prometheus:
      enabled: true
  metrics:
    tags:
      application: gathering-server

spring:
  docker:
    compose:
      enabled: false
  datasource:
    url: jdbc:mysql://gathering.cvuk42kqur71.ap-northeast-2.rds.amazonaws.com:3306/gathering
    username: root
    password: rootroot
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: false
  data:
    redis:
      host: 43.201.58.29
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

jwt:
  secretKey: dGhpc0lzQVNlY3JldEtleUZvckp3dFRva2VuVGVzdGluZzEyMzQ1Njc4OTA=
  access:
    expiration: 3600000
  refresh:
    expiration: 604800000

s3:
  credentials:
    access-key: your-access-key
    secret-key: your-secret-key
    region: ap-northeast-2
  bucket: your-bucket-name

file:
  path: /images

path: /images

chat-message-send:
  id: chat-message-send-id

chat-message-reply:
  id: chat-message-reply-id
