server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gathering
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

jwt:
  secretKey: dGhpc0lzQVNlY3JldEtleUZvckp3dFRva2VuVGVzdGluZzEyMzQ1Njc4OTA=

chat-message:
  key: chat-message-key

chat-message-send:
  id: chat-message-send-id

chat-message-reply:
  id: chat-message-reply-id
